version: '3.4'

services:
  # database
  mentor-student-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MentorStudentDb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  # api
  mentor-student-api:
    image: mentor-student-api  
    container_name: mentor-student-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mentor-student-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=MentorStudentDb;Database=MentorStudentDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;

volumes:
  sqlvolume: